name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: yarn

    - name: Build Userscript
      run: yarn build:prod

    - name: Build CSS
      run: yarn build:css

    - name: Bump Version
      run: |
        git config --global user.email "flower-q@users.noreply.github.com"
        git config --global user.name "Flower-Q"
        yarn release --release-as ${{ github.event.inputs.version }}

    - name: Push Tags
      run: git push --follow-tags origin master

    - name: Draft Release
      uses: actions/create-release@v1
      id: draft_release
      with:
        draft: true
        release_name: ${{ github.event.inputs.version }}
        tag_name: ${{ github.event.inputs.version }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Attach Userscript Meta
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }}
        asset_path: ./lib/iirose-clean-theme.meta.js
        asset_name: iirose-clean-theme.meta.js
        asset_content_type: text/javascript

    - name: Attach Userscript
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }}
        asset_path: ./lib/iirose-clean-theme.user.js
        asset_name: iirose-clean-theme.user.js
        asset_content_type: text/javascript

    - name: Attach CSS
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }}
        asset_path: ./lib/styles.css
        asset_name: styles.css
        asset_content_type: text/css
